language: minimal
services:
  - docker
install:
  - docker build -t nodejs-test -f test/nodejs.Dockerfile .
  - docker pull python:2-buster
script:
  - docker run -v "$(pwd):/docopt.js" -w /docopt.js python:2-buster bash test/docker-deno-test.sh
  - docker run -e NODE_OPTIONS='--no-warnings --experimental-modules' nodejs-test node test/nodejs_docopt_test.js
